carrd/accounts/urls.py
from accounts.views import SignUpView
from django.urls import path

app_name = "accounts"


urlpatterns = [
    path("signup", SignUpView.as_view(), name="signup"),
]

carrd/carrd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
]

carrd/pages/urls.py
from django.urls import path
from pages.views import home_view, profile_view

app_name = "pages"

urlpatterns = [
    path("", home_view, name="home"),
    path(
        "<str:username>",
        profile_view,
        name="profile",
    ),
]

carrd/accounts/models.py
from django.db import models

# Create your models here.

carrd/pages/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    text = models.TextField()

    def __str__(self):
        summary = self.text[:50] if len(self.text) >= 50 else self.text
        return summary

carrd/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User

        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )

carrd/accounts/views.py
from accounts.forms import CustomUserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView


class SignUpView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

carrd/pages/views.py
import random

from django.shortcuts import render
from pages.models import Profile


def home_view(request):
    profiles = Profile.objects.all()

    context = {}

    if len(profiles) < 10:
        context["profiles"] = profiles
    else:
        context["profiles"] = random.sample(profiles, 10)

    response = render(request, "pages/index.html", context)

    return response


def profile_view(request, username):
    try:
        profile_obj = Profile.objects.get(user__username=username)

    except Profile.DoesNotExist:
        return render(request, "pages/profile_not_found.html", {"username": username})

    paragraphs = profile_obj.text.split("\n")

    context = {
        "profile_owner_full_name": profile_obj.user.get_full_name(),
        "paragraphs": paragraphs,
    }

    return render(request, "pages/profile.html", context)

carrd/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h1>Sign Up</h1>

<form action="" method="post">
    {% csrf_token%}
    {{ form|crispy }}
    <button type="submit">Sign Up</button>
</form>
{% endblock content %}

carrd/pages/templates/pages/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
    <h1>Carrd</h1>

    {% if user.is_authenticated %}

        <p>{{ user.username }}</p>

        <a href="{% url 'password_change' %}">Change your password</a>

        <form action="{% url 'logout' %}" method="post">
            {% csrf_token%}
            <button type="submit">Log Out</button>
        </form>

    {% else %}

        <form action="{% url 'login' %}" method="get">
            {% csrf_token%}
            <button type="submit">Log In</button>
        </form>

        <form action="{% url 'accounts:signup' %}" method="get">
            {% csrf_token%}
            <button type="submit">Sign Up</button>
        </form>


    {% endif %}

    {% for profile in profiles %}
        <h2><a href="{% url 'pages:profile' profile.user.username %}">{{ profile.user.first_name }}</a></h2>
        <p>{{ profile.text|truncatechars:140 }}</p>
    {% endfor %}

{% endblock content %}

carrd/pages/templates/pages/profile.html
{% extends "base.html" %}

{% block title %}{{ profile_owner_full_name }}{% endblock title %}

{% block content %}
    <h1>{{ profile_owner_full_name}} </h1>

    {% for paragraph in paragraphs %}
        <p>{{ paragraph }}</p>
    {% endfor %}

{% endblock content %}

carrd/pages/templates/pages/profile_not_found.html
{% extends "base.html" %}

{% block title %}Profile Not Found{% endblock title %}

{% block content %}
    <h1>Profile not found...</h1>
    <p>No profiles for the username {{ username }} where found on our database.</p>
    <p><a href="{% url 'pages:home' %}">Back to home</a></p>

{% endblock content %}

carrd/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Carrd | {% block title %}Home{% endblock title %}</title>

</head>

<body>

{% block content %}
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>